[project]
name = "lab4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "np>=1.0.2",
    "numpy>=2.3.4",
    "torchvision>=0.24.1",
]
